server:
  port: ${PORT:8080}

spring:
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}

  security:
    oauth2:
      client:
        registration:
          github:
            client-id: ${OAUTH_GITHUB_ID}
            client-secret:  ${OATUH_GITHUB_SECRET}