server:
  port: ${PORT:8080}

spring:
  autoconfigure:
    exclude=: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  security:
    user:
      name: ${USERNAME}
      password: ${PASSWORD}
      roles: USER

logging:
  level:
    org.springframework.security: DEBUG

