spring:
#  datasource:
#    url: 'jdbc:postgresql://localhost:5432/bld'
#    username: 'bld'
#    password: 'root'
  datasource:
    url: jdbc:mysql://localhost:3306/spring_social?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
    username: root
    password: root
